## Ejercicio 1

In [12]:
import numpy as np
x=np.arange(21)[12:]
x

array([12, 13, 14, 15, 16, 17, 18, 19, 20])

In [16]:
#1ra manera de invertir el arreglo
x_rev=np.flip(x)
x_rev

array([20, 19, 18, 17, 16, 15, 14, 13, 12])

In [17]:
#2da manera de invertir el arreglo
x_rev2=x[::-1]#Para que vaya de 1 en 1 pero de derecha a izquierda.
x_rev2

array([20, 19, 18, 17, 16, 15, 14, 13, 12])

## Ejercicio 2

In [30]:
#Array de valores en Farenheith

TempF=np.array([0,12,45.21,34,99.91,32])
TempF

array([ 0.  , 12.  , 45.21, 34.  , 99.91, 32.  ])

In [37]:
TempC=(TempF-32)/1.8 #Conversion a F
TempC_R=np.round(Temp_C, decimals=2) #Redondear valores del array
print(TempC_R)

[-17.78 -11.11   7.34   1.11  37.73   0.  ]


## Ejercicio 3

In [42]:
array_in=np.concatenate(([0,10,20],[20,10,30]))

#se puede usar el metodo unique para eliminar valores repetidos en el array:
array_out=np.unique(array_in)
array_out

array([ 0, 10, 20, 30])